
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination: 
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.10.x
    helm:
      releaseName: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
 