apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production 
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
     
 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fiawornunobel@gmail.com
    privateKeySecretRef:
      name: "bel-crm-account-key-z4cmq"
    solvers: 
    - http01:
        ingress:
          class: nginx